# Generated by Django 5.0.6 on 2024-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicianmodel',
            name='album',
        ),
        migrations.RemoveField(
            model_name='musicianmodel',
            name='phone_no',
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='instrument_type',
            field=models.CharField(max_length=100),
        ),
    ]
